// <auto-generated />
using System;
using CheckListApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CheckList.Core.Migrations
{
    [DbContext(typeof(ProjectEntities))]
    partial class ProjectEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CheckListApp.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<long?>("FacebookId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("CheckListApp.Data.CheckAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionDscr")
                        .HasMaxLength(1000);

                    b.Property<string>("ActionText")
                        .HasMaxLength(255);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("ChangeDateTime");

                    b.Property<string>("ChangeUserName")
                        .HasMaxLength(255);

                    b.Property<string>("CompleteInd")
                        .HasMaxLength(1);

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<int>("ListId");

                    b.Property<int>("SortOrder");

                    b.HasKey("ActionId");

                    b.ToTable("CheckAction");
                });

            modelBuilder.Entity("CheckListApp.Data.CheckCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveInd")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<string>("CategoryDscr")
                        .HasMaxLength(1000);

                    b.Property<string>("CategoryText")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("ChangeDateTime");

                    b.Property<string>("ChangeUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<int>("ListId");

                    b.Property<int>("SortOrder");

                    b.HasKey("CategoryId");

                    b.ToTable("CheckCategory");
                });

            modelBuilder.Entity("CheckListApp.Data.CheckList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveInd")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<DateTime>("ChangeDateTime");

                    b.Property<string>("ChangeUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("ListDscr")
                        .HasMaxLength(1000);

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("SetId");

                    b.Property<int>("SortOrder");

                    b.HasKey("ListId");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("CheckListApp.Data.CheckSet", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveInd")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<DateTime>("ChangeDateTime");

                    b.Property<string>("ChangeUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("SetDscr")
                        .HasMaxLength(1000);

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("SortOrder");

                    b.Property<int?>("TemplateSetId");

                    b.HasKey("SetId");

                    b.ToTable("CheckSet");
                });

            modelBuilder.Entity("CheckListApp.Data.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gender");

                    b.Property<string>("IdentityId");

                    b.Property<string>("Locale");

                    b.Property<string>("Location");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CheckListApp.Data.TemplateAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionDscr")
                        .HasMaxLength(1000);

                    b.Property<string>("ActionText")
                        .HasMaxLength(255);

                    b.Property<int?>("CategoryId");

                    b.Property<DateTime>("ChangeDateTime");

                    b.Property<string>("ChangeUserName")
                        .HasMaxLength(255);

                    b.Property<string>("CompleteInd")
                        .HasMaxLength(1);

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<int>("SortOrder");

                    b.HasKey("ActionId");

                    b.ToTable("TemplateAction");
                });

            modelBuilder.Entity("CheckListApp.Data.TemplateCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveInd")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<string>("CategoryDscr")
                        .HasMaxLength(1000);

                    b.Property<string>("CategoryText")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("ChangeDateTime");

                    b.Property<string>("ChangeUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<int>("ListId");

                    b.Property<int>("SortOrder");

                    b.HasKey("CategoryId");

                    b.ToTable("TemplateCategory");
                });

            modelBuilder.Entity("CheckListApp.Data.TemplateList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveInd")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<DateTime>("ChangeDateTime");

                    b.Property<string>("ChangeUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("ListDscr")
                        .HasMaxLength(1000);

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("SetId");

                    b.Property<int>("SortOrder");

                    b.HasKey("ListId");

                    b.ToTable("TemplateList");
                });

            modelBuilder.Entity("CheckListApp.Data.TemplateSet", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveInd")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<DateTime>("ChangeDateTime");

                    b.Property<string>("ChangeUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("SetDscr")
                        .HasMaxLength(1000);

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("SortOrder");

                    b.HasKey("SetId");

                    b.ToTable("TemplateSet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CheckListApp.Data.Customer", b =>
                {
                    b.HasOne("CheckListApp.Data.AppUser", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CheckListApp.Data.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CheckListApp.Data.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CheckListApp.Data.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CheckListApp.Data.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
