# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build Database Objects Only to existing resources
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: singleEnvironment
  default: 'false'
- name: appFolderName
  default: ''
- name: appSolutionName
  default: ''
- name: appProjectName
  default: ''
- name: loginAccountType
  default: 'SVC_PRINCIPAL'
- name: addFirewallRule
  type: boolean
  default: true

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildDacPac
  displayName: Build DACPAC
  jobs:
  - template: ../jobs/dacpac-build-job.yml
    parameters:
      environmentName: 'DEV'
      appFolderName: ${{ parameters.appFolderName }}
      appSolutionName: ${{ parameters.appSolutionName }}
      appProjectName: ${{ parameters.appProjectName }}
      artifactName: 'dacpac'

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: Deploy${{ environmentName }}Schema
    displayName: Deploy ${{ environmentName }} Schema
    # Condition is build complete and a single environment is being deployed, 
    # or the environment is 'dev', or if qa/prod, the previous stage (dev->qa or qa->prod) succeeded
    condition: or(eq(${{ parameters.singleEnvironment }}, 'true'), and(eq(upper('${{ environmentName }}'), 'QA'), succeeded('DeployDEVSchema')), and(eq(upper('${{ environmentName }}'), 'PROD'), succeeded('DeployQASchema')))
    jobs:
    - template: ../jobs/dacpac-deploy-job.yml
      parameters:
        environmentName: ${{ environmentName }}
        artifactName: 'dacpac'
        appProjectName: ${{ parameters.appProjectName }}
        loginAccountType: ${{ parameters.loginAccountType }}
        addFirewallRule: ${{ parameters.addFirewallRule }}

  # Grant App Service Managed Identity access to the database after DACPAC deploy
  - stage: Grant${{ environmentName }}Identity
    displayName: Grant ${{ environmentName }} Identity
    dependsOn: Deploy${{ environmentName }}Schema
    jobs:
    - template: ../jobs/run-sql-job.yml
      parameters:
        environmentName: ${{ environmentName }}
        sqlFolderName: 'src\CheckList.Database\Patch\'
        sqlFileName: 'Add-App-User-Rights.sql'
        runInDatabase: $(SQL_DATABASE_NAME)
        loginAccountType: ${{ parameters.loginAccountType }}
        addFirewallRule: ${{ parameters.addFirewallRule }}
        sqlCmdVariables:
          - 'AppIdentityName=$(APP_NAME)$(INSTANCE_NUMBER)-${{ lower(environmentName) }}'
